batch_size: 16
epoch: 200
learning_rate: 0.05
gpu: 0
num_point: 1024
optimizer: SGD
weight_decay: 1e-4
normal: False

defaults:
  - _self_
  - model: Hengshuang

hydra:
  run:
    dir: log/cls/${model.name}

  sweep:
    dir: log/cls
    subdir: ${model.name}